<!-- <div class="footer-container">
	<div class="footer-bottom">
  <div class="grid"><div class="grid__inner">
    <div class="grid__item grid__item--tablet-up-4 footer-bottom__links pull-right">
      
    <a href="<?php echo $this->getUrl('retailerkittools/dashboard') ?>"><?php echo $this->__('Free Tools') ?></a>
    <a href="<?php echo $this->getUrl('retailerkittools/index/companyinfo') ?>"><?php echo $this->__('Company Information') ?></a>
    <a href="<?php echo $this->getUrl('retailerkittools/index/shippingsender') ?>"><?php echo $this->__('Sender Information') ?></a>
    <a href="<?php echo $this->getUrl('retailerkittools/index/vendors') ?>"><?php echo $this->__('Vendors')?></a>

</div></div></div></div>
</div> -->
<div class="container">
  <div class="row">
  <hr>
    <div class="col-lg-12">
      <div class="col-md-8">
        <a href="<?php echo $this->getUrl('retailerkittools/dashboard') ?>"><?php echo $this->__('Free Tools') ?></a> | <a href="<?php echo $this->getUrl('retailerkittools/index/companyinfo') ?>"><?php echo $this->__('Company Information') ?></a> | <a href="<?php echo $this->getUrl('retailerkittools/index/shippingsender') ?>"><?php echo $this->__('Sender Information') ?></a> | <a href="<?php echo $this->getUrl('retailerkittools/index/vendors') ?>"><?php echo $this->__('Vendors')?></a>
      </div>
      <address class="copyright"><?php echo $this->getCopyright() ?></address>
    </div>
  </div>
</div>