<?php
	$helper = Mage::helper('retailerkittools'); 
?>
<style type="text/css">
.label {
    margin-bottom: -50px;
    padding-left: 5px;
    padding-top: 2px;
    position: absolute;
    color: #908f8f;    
    z-index: 999;
    opacity: 0;
    font-weight: 100;
}
.form-control {
    height: 100%;
    padding-bottom: -10px;
}
.input-group-btn:last-child > .form-control {
  margin-left: -1px;
  width: 100%;
}
</style>
<section class="section section--border" id="ToolContent">
   	<div class="page-width">
      	<div class="title-section">
         	<div class="section-heading">
            	<h1 class="section-heading__heading heading--1"><?php echo $this->__('Shipping Label Maker') ?></h1>
         	</div>
      	</div>
      	<div class="section-block col-md-12 ">
	      	<form id="ShippingLabelForm" class="js-form-validate js-submit-async" data-validation-event="Shipping Label" data-tool="shipping label" action="<?php echo $this->getUrl('retailerkittools/index/shippinglabel') ?>" accept-charset="UTF-8" method="post" novalidate="">
		        <div class="form-section col-md-12">
		            <div class="form-header">
		               <h3 class="form-header__heading"><?php echo $this->__('Enter sender information') ?></h3>
		               <div class="form-header__status step-counter">
		                  <span class="step-counter__label heading--5"><?php echo $this->__('Step 1 of 3') ?></span>
		                  <span class="step-counter__dots dots-container">
		                  <span class="dots-container__dot dots-container__dot--active"></span>
		                  <span class="dots-container__dot "></span>
		                  <span class="dots-container__dot "></span>
		                  </span>
		               </div>
		            </div>
		            <div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('First Name') ?></small>
				  				<input type="text" name="sender[first_name]" id="sender_first_name" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','first_name'); ?>" class="form-control required-entry" placeholder="First Name" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Last Name') ?></small>
				  				<input type="text" name="sender[last_name]" id="sender_last_name" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','last_name'); ?>" class="form-control required-entry" placeholder="Last Name" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Sender email address') ?></small>
				   				<input type="email" name="sender[email]" id="sender_email" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','email'); ?>" class="form-control required-entry validate-email" placeholder="Sender email address" >
				   			</div>
				  		</div>
				   	</div>
				   	<div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-8">				
								<small class="label" for="input"><?php echo $this->__('Address') ?></small>
				  				<input type="text" name="sender[address]" id="sender_address" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','address'); ?>" class="form-control required-entry" placeholder="Address" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('City') ?></small>
				   				<input type="text" name="sender[city]" id="sender_city" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','city'); ?>" class="form-control required-entry" placeholder="City" >
				   			</div>
				  		</div>
				   	</div>
				   	<div class="section-input-field col-md-12">
				   		<div class="form-input-inline">		
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Zip/postal code') ?></small>
				  				<input type="text" name="sender[zip]" id="sender_zip" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','zipcode'); ?>" class="form-control" placeholder="Zip/postal code" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Country') ?></small>
				  				<?php echo $this->getCountryHtmlSelect() ?>
				  			</div>				   			
				   			<div class="form-group col-md-4">
				   				<div class="input-box">				
									<small class="label" for="input"><?php echo $this->__('State/Province') ?></small>
				                    <select id="sender_province_id" name="sender[province_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
				                       <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				                    </select>
				                    <script type="text/javascript">
				                    //<![CDATA[
				                        $('sender_province_id').setAttribute('defaultValue',  "<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','state_id') ?>");
				                    //]]>
				                    </script>
									<small class="label" for="input"><?php echo $this->__('State/Province') ?></small>
				                    <input type="text" id="sender_province" class="form-control" name="sender[province]" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','state'); ?>"  placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
				                </div>
				   			</div>
				   		</div>
				   	</div>
		        </div>
			   	<div class="form-section col-md-12">
				   	<div class="form-header">
				   		<h3 class="form-header__heading"><?php echo $this->__('Enter receiver information') ?></h3>
				   		<div class="form-header__status step-counter">
				   			<span class="step-counter__label heading--5"><?php echo $this->__('Step 2 of 3') ?></span>
				   			<span class="step-counter__dots dots-container">
					   			<span class="dots-container__dot dots-container__dot--active"></span>
					   			<span class="dots-container__dot dots-container__dot--active"></span>
					   			<span class="dots-container__dot "></span>
				   			</span>
				   		</div>
				  	</div>
				  	<div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('First Name') ?></small>
				  				<input type="text" name="receiver[first_name]" id="receiver_first_name" class="form-control required-entry" placeholder="First Name" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Last Name') ?></small>
				  				<input type="text" name="receiver[last_name]" id="receiver_last_name" class="form-control required-entry" placeholder="Last Name" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Receiver email address') ?></small>
				   				<input type="email" name="receiver[email]" id="receiver_email" class="form-control required-entry validate-email" placeholder="Receiver email address" >
				   			</div>
				  		</div>
				  	</div>
				  	<div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-8">				
								<small class="label" for="input"><?php echo $this->__('Address') ?></small>
				  				<input type="text" name="receiver[address]" id="receiver_address" class="form-control required-entry" placeholder="Address" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('City') ?></small>
				   				<input type="text" name="receiver[city]" id="receiver_city" class="form-control required-entry" placeholder="City" >
				   			</div>
				  		</div>
				   	</div>
				   	<div class="section-input-field col-md-12">
				   		<div class="form-input-inline">
				   			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Zip/postal code') ?></small>
				  				<input type="text" name="receiver[zip]" id="receiver_zip" class="form-control" placeholder="Zip/postal code" >
				  			</div>
				  			<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Country') ?></small>
				  				<?php echo $this->getCountryHtmlSelectForCustomer() ?>
				  			</div>
				   			<div class="form-group col-md-4">
				   				<div class="input-box">				
									<small class="label" for="input"><?php echo $this->__('State/Province') ?></small>
				                    <select id="receiver_province_id" name="receiver[province_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
				                       <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				                    </select>
				                    <script type="text/javascript">
				                    //<![CDATA[
				                        $('receiver_province_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
				                    //]]>
				                    </script>				
									<small class="label" for="input"><?php echo $this->__('State/Province') ?></small>
				                    <input type="text" id="receiver_province" class="form-control" name="receiver[province]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
				                </div>
				   			</div>
				   		</div>
				   	</div>
			   	</div>
			   	<div class="form-section col-md-12">
				   	<div class="form-header">
					   	<h3 class="form-header__heading"><?php echo $this->__('Enter shipping information') ?></h3>
					   	<div class="form-header__status step-counter">
						   	<span class="step-counter__label heading--5"><?php echo $this->__('Step 3 of 3') ?></span>
						   	<span class="step-counter__dots dots-container">
							   	<span class="dots-container__dot dots-container__dot--active"></span>
							   	<span class="dots-container__dot dots-container__dot--active"></span>
							   	<span class="dots-container__dot dots-container__dot--active"></span>
						   	</span>
					   	</div>
				   	</div>
				   	<div class="section-input-field col-md-12">
					   	<div class="form-input-inline">
					   		<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Shipping date') ?></small>
						   		<input type="text" name="shipping_date" id="shipping_date" value="<?php echo date("Y-m-d")?>" class="form-control" placeholder="Shipping date" >
						   	</div>
						   	<div class="form-group col-md-4">				
								<small class="label" for="input"><?php echo $this->__('Tracking number') ?></small>
						   		<input type="text" name="tracking_number" id="tracking_number" class="form-control required-entry" placeholder="Tracking number" >
						   	</div>
						   	<div class="form-group col-md-3" style="padding-right: 0">				
								<small class="label" for="input"><?php echo $this->__('Package weight') ?></small>
						   		<input type="text" name="weight" id="weight" class="form-control required-entry validate-number" placeholder="Package weight" style="border-radius: 4px 0 0 4px;">
						   	</div>
					   		<div class="input-group-btn" style="padding-right: 15px;">
						      	<select class="form-control" name="unit_measurement" style="border-radius: 0 4px 4px 0;">
							        <option value="g">g</option>
							        <option value="kg">kg</option>
							        <option value="lbs">lbs</option>
						      	</select>
						    </div>
					   	</div>
					</div>
			   	</div>
	   			<div class="form-section col-md-12">
	   				<input type="submit" name="commit" value="Create shipping label" class="btn btn-primary btn-lg pull-right">
	   			</div>
	   		</form>
	   	</div>
   	</div>
</section>
<script type="text/javascript">
//<![CDATA[
    // var formId = 'InvoiceGeneratorForm';
    // var myForm = new VarienForm(formId, true);
    // var postUrl = '<?php echo $this->getUrl("retailerkittools/index/printinvoice") ?>';
    // function doAjax() {
    //     if (myForm.validator.validate()) {
    //         new Ajax.Updater(
    //             { success:'formSuccess' }, postUrl, {
    //                 method:'post',
    //                 asynchronous:true,
    //                 evalScripts:false,
    //                 onComplete:function(request, json) {
    //                 	if (request.responseText.isJSON()) {
    //                 var res = request.responseText.evalJSON();
    //                 var printContents = res.html;
				//      var originalContents = document.body.innerHTML;

				//      document.body.innerHTML = printContents;

				//      window.print();

				//      document.body.innerHTML = originalContents;
    //             }
    //                     // Element.hide(formId);
    //                     // Element.show('formSuccess');
    //                 },
    //                 onLoading:function(request, json){
    //                     // Element.show('formLoader');
    //                 },
    //                 parameters: $(formId).serialize(true),
    //             }
    //         );
    //     }
    // }
    
    // new Event.observe(formId, 'submit', function(e){
    //     e.stop();
    //     doAjax();
    // });

	var shippingLabelForm = new VarienForm('ShippingLabelForm');
    new RegionUpdater('sender_country', 'sender_province', 'sender_province_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    new RegionUpdater('receiver_country', 'receiver_province', 'receiver_province_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>

  Calendar.setup({
  inputField : 'shipping_date',
  ifFormat : '%Y-%m-%d',
  button : 'date_from_trig',
  align : 'Bl',
  singleClick : true
  });


$$('.form-control').each(function(el){
	if(el.previous('.label')){
		if(el.value.length > 0){
			el.previous('.label').style.opacity = '1';
		}
		el.observe('keyup', function(e) {
			if(el.value.length > 0){
				el.previous('.label').style.opacity = '1';
			}else{
				el.previous('.label').style.opacity = '0';
			}
		});
	}
});
</script>
